# Configuration Nixpacks pour UNPI - utilise notre nginx.conf personnalisé

providers = ["php"]

[phases.setup]
nixPkgs = [
  "nginx", 
  "php82", 
  "php82Extensions.pdo", 
  "php82Extensions.pdo_mysql", 
  "php82Extensions.mysqli", 
  "php82Extensions.mbstring", 
  "php82Extensions.curl", 
  "php82Extensions.gd", 
  "php82Extensions.zip", 
  "php82Extensions.xml", 
  "php82Extensions.openssl",
  "php82Extensions.session"
]

[phases.build]
cmds = [
  "echo 'Configuration personnalisée UNPI...'",
  "ls -la /app/",
  "echo 'Vérification de nginx.conf...'",
  "test -f /app/nginx.conf && echo 'nginx.conf trouvé' || echo 'nginx.conf manquant'",
  "echo 'Préparation du répertoire nginx...'",
  "mkdir -p /tmp/nginx-config",
  "if [ -f /app/nginx.conf ]; then cp /app/nginx.conf /tmp/nginx-config/nginx.conf && echo 'nginx.conf copié vers /tmp/nginx-config/'; fi"
]

[phases.install]
cmds = [
  "echo 'Installation des dépendances PHP...'",
]

[start]
cmd = """
echo 'Démarrage de UNPI avec configuration nginx personnalisée...' && \
echo 'Recherche de nginx.conf...' && \
if [ -f /tmp/nginx-config/nginx.conf ]; then \
  echo 'nginx.conf trouvé dans /tmp/nginx-config/, copie vers /etc/nginx/nginx.conf' && \
  cp /tmp/nginx-config/nginx.conf /etc/nginx/nginx.conf && \
  echo 'Configuration nginx personnalisée appliquée avec succès' && \
  echo 'Vérification du contenu:' && \
  grep -A 5 -B 5 'location /' /etc/nginx/nginx.conf || echo 'Pas de location / trouvé'; \
elif [ -f /app/nginx.conf ]; then \
  echo 'nginx.conf trouvé dans /app/, copie vers /etc/nginx/nginx.conf' && \
  cp /app/nginx.conf /etc/nginx/nginx.conf && \
  echo 'Configuration nginx personnalisée appliquée avec succès'; \
else \
  echo 'ERREUR: nginx.conf non trouvé' && \
  echo 'Contenu de /app/:' && \
  ls -la /app/ && \
  echo 'Contenu de /tmp/nginx-config/:' && \
  ls -la /tmp/nginx-config/ 2>/dev/null || echo 'Répertoire /tmp/nginx-config/ inexistant' && \
  echo 'Utilisation de la configuration nginx par défaut'; \
fi && \
echo 'Test de la configuration nginx...' && \
nginx -t && \
echo 'Démarrage de PHP-FPM...' && \
php-fpm -D && \
echo 'Démarrage de nginx...' && \
nginx -g 'daemon off;'
"""

