# Configuration Nixpacks pour UNPI - utilise notre nginx.conf personnalisé

providers = ["php"]

[phases.setup]
nixPkgs = [
  "nginx", 
  "php82", 
  "php82Extensions.pdo", 
  "php82Extensions.pdo_mysql", 
  "php82Extensions.mysqli", 
  "php82Extensions.mbstring", 
  "php82Extensions.curl", 
  "php82Extensions.gd", 
  "php82Extensions.zip", 
  "php82Extensions.xml", 
  "php82Extensions.openssl",
  "php82Extensions.session"
]

[phases.build]
cmds = [
  "echo 'Configuration personnalisée UNPI...'",
  "ls -la /app/",
  "echo 'Vérification de nginx.conf...'",
  "test -f /app/nginx.conf && echo 'nginx.conf trouvé' || echo 'nginx.conf manquant'",
  "echo 'Préparation du répertoire nginx...'",
  "mkdir -p /tmp/nginx-config",
  "if [ -f /app/nginx.conf ]; then cp /app/nginx.conf /tmp/nginx-config/nginx.conf && echo 'nginx.conf copié vers /tmp/nginx-config/'; fi"
]

[phases.install]
cmds = [
  "echo 'Installation des dépendances PHP...'",
]

[start]
cmd = "bash -c 'if [ -f /tmp/nginx-config/nginx.conf ]; then cp /tmp/nginx-config/nginx.conf /etc/nginx/nginx.conf; elif [ -f /app/nginx.conf ]; then cp /app/nginx.conf /etc/nginx/nginx.conf; fi && nginx -t && php-fpm -D && nginx -g \"daemon off;\"'"

